### ISSUE TITLE
Crash at splash screen

### ISSUE THREAD

**Issue by beckno9** [Podshot/MCEdit-Unified#956] opened 2018-10-24 12:55 UTC
#### Error message from the console:
```
D:\MCEdit-Unified>mcedit
Data Dir: D:\MCEdit-Unified
Running in fixed mode. Support files are in your Documents folder.
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Splash load...
Traceback (most recent call last):
  File "mcedit.py", line 69, in <module>
LookupError: unknown encoding: cp65001
[11916] Failed to execute script mcedit

D:\MCEdit-Unified>mcedit
Data Dir: D:\MCEdit-Unified
Running in fixed mode. Support files are in your Documents folder.
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Splash load...
Traceback (most recent call last):
  File "mcedit.py", line 69, in <module>
LookupError: unknown encoding: cp65001
[13484] Failed to execute script mcedit
```

I just open the software and simply get these errors. I tried release 1.5.6.0 and the testing version 1.6.0.53. These are the two possible errors I'm able to get. 
Please help me to check what happened, thank you.

**Comment by Podshot** [comment] 2018-10-24 14:54
Have you set a custom system encoding for your machine or changed it from the default value?

**Comment by Pharap** [comment] 2018-10-27 08:39
Aside from the minor OS difference (enterprise vs home edition), this seems to be a dupe of #949

**Comment by beckno9** [comment] 2018-11-04 02:59
> Have you set a custom system encoding for your machine or changed it from the default value?

![123](https://user-images.githubusercontent.com/18245817/47959496-af55a100-e020-11e8-8358-33ad3f6055d1.PNG)

**Comment by gentlegiantJGC** [comment] 2018-12-30 12:57
duplicate of #949. Looks to be a Unicode based issue

**Closed as completed by gentlegiantJGC** 2018-12-30 12:57 UTC
Labels: Windows
