### ISSUE TITLE
MCEdit won't load my save properly

### ISSUE THREAD

**Issue by yemo1823** [Podshot/MCEdit-Unified#940] opened 2018-08-09 10:16 UTC
#### A screenshot or full text of the error from the console:
![image](https://user-images.githubusercontent.com/42237618/43892981-2a503508-9bd6-11e8-9662-943734eca2df.png)

## Read before submitting
If we are not able to reproduce the error, we may ask for you to submit a world so we can test it. Same process for schematics.
If you have included enough information for each section, please delete the above header and all the text below.

**Comment by gentlegiantJGC** [comment] 2018-08-09 10:35
Duplicate of #938

**Closed as completed by gentlegiantJGC** 2018-08-09 10:35 UTC

**Comment by yemo1823** [comment] 2018-08-09 11:55
But I can't do anything with it, even not in 1.11.2
@gentlegiantJGC

**Comment by gentlegiantJGC** [comment] 2018-08-11 11:44
You said in the report that the world was opened in 1.13 right? So Minecraft has converted the world to the 1.13 format. MCedit doesn't currently support this format so it can't open it
