### ISSUE TITLE
Cannot Rotate Downloaded Schematics

### ISSUE THREAD

**Issue by SeberHusky** [Podshot/MCEdit-Unified#829] opened 2017-07-18 08:28 UTC
Have an error in MC Edit.  I am using 1.5.6.0 version, with Minecraft 1.12 and when I downloaded a schematic from Minecraft Schematics and imported it, and then tried to rotate it, I get the following error: <function rotate at 0x0000000000ADE50B8>:TypeError("unhashable type: '_NBT.TAG_String'",)

I clicked into the DOS window for MC Edit and I seen there seems to be an issue that it does not like with DEFS_ENTITIES_PAINTING and DEFS_ENTITIES_ITEM_FRAME.

**Comment by Julienc249** [comment] 2017-07-22 16:16
I have tracked my issue to be the same as yours, 
Do signs also lose their information?

**Comment by SeberHusky** [comment] 2017-07-22 17:42
Yes, that has happened for awhile. If I remember, you can still see what the sign said in the code when clicking the sign in MCEdit and write that down and reedit the sign in game, but otherwise the signs will appear blank in game and in MCEdit.

**Comment by LaChal** [comment] 2017-07-22 18:09
This issue *shall* be fixed.

We'll check on our side to confirm.

**Comment by SeberHusky** [comment] 2017-07-22 18:42
I noticed it does rotate after it is placed in game. A workaround I do for now is that I look at the outline and guess which way the building is facing, import and place the building in the air, check if it's in the right position, if not I select it and rotate again, and then move it down to the ground level.

**Comment by Azounstone** [comment] 2017-07-27 12:55
Any news on this topic as I am trying to rotate a lot of schematics and am unable to do so. I am guessing this is connected to this thread:
![error 1](https://user-images.githubusercontent.com/9461336/28671006-102940a2-72d3-11e7-8bd3-050879dcafb5.jpg)
![error 2](https://user-images.githubusercontent.com/9461336/28671007-102ff14a-72d3-11e7-8952-7c07ab3382ea.jpg)
Is there anything I can do to fix this as I have over a thousand items I need to import and position in a world and not being able to rotate them is stopping me from doing it.

**Comment by SeberHusky** [comment] 2017-07-27 19:57
Yes that is the exact error. And I posted a workaround above.

**Comment by Azounstone** [comment] 2017-07-27 21:25
After importing a schematic I do not know how you rotate it so am unable to make sense of your workaround. Please explain how you rotate something that has been imported?

**Comment by Azounstone** [comment] 2017-07-30 20:52
Any news on this one?

Thanks :)

**Comment by LaChal** [comment] 2017-08-05 13:08
@Azounstone The fact is the schematic is imported, but the display is not updated correctly in MCEdit if you rotate it until you click the `Import` button.
Also, MCEdit do not rotate signs because of the bug you signalled. I confess it's annoying, and can be really tedious to place them again in MCEdit or the game :/

By the way, are you running from source?

The issue is fixed in MCEdit sources.

**Comment by Azounstone** [comment] 2017-08-05 13:35
@LaChal Sorry I do not really understand exactly what you mean about the display not being updated.

I am not running from source and do not know how to do this so if you could explain how it would be really appreciated if this issues is fixed when doing so?

Thanks for your help with this :)

**Comment by LaChal** [comment] 2017-08-05 13:50
The green bounding box is rotated, but not the blocks. It's only a graphical bug due to the un-rotatable signs one. The blocks actually get rotated.

If you want to run from source, just refer to the readme :smile:
Basically, install Python 2.7 (64bit is my recommendation if you're on 64bit system) and the dependencies. The virtual environment is optional, unless you're developing Python programs and want to isolate their dependencies.

Starting MCEdit can be done using the .bat file once you got the sources.

**Comment by Azounstone** [comment] 2017-08-05 14:27
@LaChal Do you know when a new version will be released that fixes this?

With regards to running from source where is this readme you mention and what are the dependecies etc?

I think it might be easier for me to use the new version you release with a fix if it will be soon but I will wait for your response with regards to my previous 2 questions.

Thanks again :)

**Comment by LaChal** [comment] 2017-08-05 14:33
The readme is MCEdit one (the long text you can see below the file list of this repo), and the dependencies are listed in :wink:

By the way, no date yet for next release...

**Comment by Azounstone** [comment] 2017-08-05 14:39
@LaChal Thanks for your help with this and I'll try to use it from source but suspect I will make a mess of it in which case I will just have to wait for a fixed new release which is a shame as I have hundreds and hundreds of schematics I need to import, rotate and adjust. Probably over a thousand actually so a working release would be brilliant!

Thanks!

**Comment by Azounstone** [comment] 2017-08-05 14:40
@LaChal Just looked at the readme for using it from source and it is way over my head. Not a chance of me being able to use it so I am in your hands and waiting for a fix.

Thanks :)

**Comment by LaChal** [comment] 2017-08-05 15:08
Since I don't know the next release date, here is the steps to run from source:

1. Get the MCEdit source archive: Click on the `Clone or download` button on the repository main page, and choose `Download ZIP`.
2. Unpack the ZIP somewhere.
3. Install Python 2.7 for you platform. Pay attention to install Python 64 bit on a Windows 64 bit!
4. Optional, but recommended, add the folder where `python.exe` is to your `Path` environment variable. It will let you invoke Python from a command prompt using `python` instead of writing the whole path to `python.exe`. (Python installer may ask you to update the `Path`; just let it do!)
5. Open a command prompt and enter all the `easy_install` commands to install the Python packages.
6. In the same command prompt, enter the `pip` and `python` commands to get binaries for NBT and PNG.

To run MCEdit, open the folder where MCEdit is and double click on `mcedit.bat`.

**Comment by Azounstone** [comment] 2017-08-06 18:09
@LaChal Thanks for the detailed reply and trying to help.

Sadly I do not know what or where the path environment variable is. I also have no idea what these easy_install commands are you mention and the same goes for pip and python commands you mentioned.

Sadly it would seem we must delay work on our 4th adventure map until you release the next version of this excellent product that does not have this graphical issue with importing schematics.

I do hope it will not be too long as it means we are twiddling our thumbs waiting :)

Thanks again for your help :)

**Comment by Azounstone** [comment] 2017-09-01 09:02
@LaChal I thought I would ask if there is any news on a new release as a month has passed (nearly) since last time this was commented upon?

**Comment by Podshot** [comment] 2017-10-23 18:27
@Azounstone We're currently working on finishing MCPE support, adding some more features, and fixing bugs that have been around for a decent amount of time. We're hoping to have a release out sometime soon, but we want this release to be the most stable one we've had, so it may be even later

**Comment by Azounstone** [comment] 2017-11-21 14:23
@Podshot We have been waiting for nearly 4 months for this issue to be fixed so I was wondering if we are any closer to the new release that fixes this?

**Comment by Podshot** [comment] 2017-11-22 16:12
@Azounstone We've been busy trying to prepare for upcoming changes to Minecraft, but we now have testing releases here: https://github.com/Podshot/MCEdit-Unified-Preview/releases/tag/MCEdit-Unified-1.6.0.13-testing

Make sure to backup any world that you will open with that testing release! See if that release fixes your issue.

**Comment by Azounstone** [comment] 2017-11-22 21:47
@Podshot Many thanks for responding and giving an update about this.

I can't afford to run the risk of something being broken/corrupted so will wait for a version that is live and fixes the issue with rotating schematics and also command blocks being imported with no data within.

Just to confirm the fix for rotating schematics fixes the issue with command blocks I trust?

**Comment by Podshot** [comment] 2017-12-03 06:43
@Azounstone Yes, we have confirmed that when importing command blocks from a schematic their data is also imported

**Comment by Azounstone** [comment] 2017-12-03 14:28
@Podshot This is excellent news and I look forward to the release version :)

**Comment by Julienc249** [comment] 2017-12-03 16:20
I am also extremely glad that this issue will finally be fixed and that we will get a new release of mcedit!

**Comment by allamassal** [comment] 2017-12-17 17:28
This happens to all schematics with entities, see #880

**Comment by naor2013** [comment] 2018-04-01 21:17
Fixed with https://github.com/Podshot/MCEdit-Unified/commit/a706088d13507cec6b870add239ad51041b9eb27

**Closed by naor2013** 2018-04-01 21:17 UTC
Labels: Bug

**Comment by Azounstone** [comment] 2018-04-01 21:42
Do you have a copy of the revised file I can download to add to my version of MCEdit so I can start to use the import feature again please @Podshot or will you be releasing a new version of MCEdit as it has been a long time since it was updated and I have been waiting since July last year for this :)

**Comment by Podshot** [comment] 2018-04-01 21:45
@Azounstone We do not have a set date on when the next full-release version will be ready, but there will be a new testing build this Friday that will have these fixes

**Comment by naor2013** [comment] 2018-04-01 22:18
A testing release with the all the latest fixes here: https://github.com/Podshot/MCEdit-Unified-Preview/releases/tag/MCEdit-Unified-1.6.0.31-testing
Just remember, it's still a beta release so backup all your worlds before using it and we would appreciate bug reports! :D

**Comment by Azounstone** [comment] 2018-04-02 21:42
@naor2013 Thanks for the link but I must not understand fully as I downloaded it and tried to find the schematic.py file so I can replace the one in my current version but there doesn't seem to be one.

Guess I will just have to wait longer for a full release.

**Comment by naor2013** [comment] 2018-04-02 21:58
I don't think this file will be visible even in release because the release will only be an exe file like the testing release is... Why do you need to change that file?

**Comment by Azounstone** [comment] 2018-04-03 11:08
I must not understand this as I assumed this file fixed the issue because @naor2013 stated that the issue was fixed with ([a706088](https://github.com/Podshot/MCEdit-Unified/commit/a706088d13507cec6b870add239ad51041b9eb27)) and this is the file I referenced in my reply earlier.

**Comment by Podshot** [comment] 2018-04-03 11:15
@Azounstone This issue has been fix via that commit, but due to the differences between the various small changes in every release and compilation of MCEdit, you cannot swap compiled files for those of a newer/older version. Thus you cannot “hot-swap” fixes from a newer version to an older version, you will just have to redownload the newer release and run that one instead

**Comment by Azounstone** [comment] 2018-04-03 11:35
@Podshot Many thanks for taking the time to explain this, much appreciated.

I used the testing build to see if it has fixed the issue and it has indeed done so however I noticed that command blocks in the schematic lose their contents when imported. Is this intended or still an issue being looked at?

**Comment by Azounstone** [comment] 2018-07-11 22:52
@Podshot Hi, hope you are well :)

Any idea when a new release will be launched that addresses this issue instead of the beta version https://github.com/Podshot/MCEdit-Unified-Preview/releases/tag/MCEdit-Unified-1.6.0.31-testing

Hope to hear some positive news in due course.

thanks again for the great work you do on this excellent product :)
